source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails'

gem 'haml_coffee_assets'
gem 'rails-backbone'
gem 'tbone'
gem 'tbone-devise'
gem 'rabl'
gem 'mongoid'
gem 'cancan'
gem 'devise'
gem 'kaminari'
gem 'twitter-bootstrap-rails'
gem 'redcarpet'
gem 'devise-i18n'
gem 'requirejs-rails'
gem 'haml-rails'
gem 'i18n-js', '~>3.0.0rc2'
gem 'jquery-rails'
gem 'awesome_print'
gem 'less-rails'
gem 'therubyracer'
gem 'uglifier'
